services:
    # PHP Service
    php:
        build: .
        container_name: php
        volumes:
            - ./target:/var/www/html
            - ./php:/app
            - ./php/php.ini:/usr/local/etc/php/php.ini
        ports:
            - '$PORT:$PORT'
        environment:
            TARGET: /var/www/html
            OUTNAME: $OUTNAME
            PORT: $PORT
